<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../DecompileForge.Contracts/DecompileForge.Contracts.csproj" />
    <ProjectReference Include="../DecompileForge.Core/DecompileForge.Core.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="DiffPlex" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
